#!/bin/sh
if [ "$1" = "start" ] ; then

export SERVER=$HOST
export TOURGEEK=/space/web/tourgeek
export POLICY_ALL=$TOURGEEK/bin/policy/policy.all
export VERSION=0.7.7-SNAPSHOT
export CLASSPATH=$TOURGEEK/WEB-INF/lib/jbundle-base-screen-control-servlet-$VERSION.jar:$TOURGEEK/WEB-INF/lib/*:/usr/local/java/web/glassfish/glassfish/lib/javaee.jar
export COMMAND="java -classpath \
$CLASSPATH \
-Xms256m -Xmx512m -Djava.rmi.server.codebase=http://$SERVER/classes/ \
-Djava.security.policy=$POLICY_ALL org.jbundle.server.Server messageserver=true \
appname=org.jbundle.main.msg.app.MessageServerActivator provider=$SERVER"
su -l glassfish -c "$COMMAND" &

elif [ "$1" = "stop" ] ; then

echo stop it

fi
